name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: lizlovelace
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: lizlovelace/liz-homepage:latest

    - name: Trigger Webhook
      if: success()
      run: |
        curl -X POST -H 'Content-Type: application/json' -H 'X-Hub-Signature: sha1=$(echo -n ${{ secrets.WEBHOOK_SECRET }} | openssl dgst -sha1 -hmac - | cut -d' ' -f2)' --data '{"ref": "refs/heads/main"}' ${{ secrets.WEBHOOK_URL }}
